########################################
#### Define file Types             #####
########################################
services:
    phpbbgallery.core.files.type.multiformtest:
        class: phpbbgallery\core\file\types\multiform
        shared: false
        arguments:
            - '@files.factory'
            - '@language'
            - '@php_ini'
            - '@plupload'
            - '@request'